### ISSUE TITLE
Feedback voltage issue

### ISSUE THREAD

**Issue by ColinDavies71** [timperi/c64-wedge-psu-pcb#1]
Hello.   What a great little project that you have here and thanks for sharing this. I'm quite new to gtihub so please excuse me if I'm not going about this in the correct way.   I've just downloaded the project to have a look at and I notice that the feedback circuit does not look right to me.  I also see that you have made a correction for this but not tried to verify it, However, it doesn't reflect in the PCB schematic.   

The voltage divider circuit, specifically R3 needs to be connected from the FB line to GND and not from the +ve on C2 to GND. All I see is that the feedback line is just going back via a 200R resistor and not being divided, while R3 is just acting as a load on the 5v in between the two inductors.

I've edited the schematic which I think will solve the problem and enclose that along with a screenshot.

Kind Regards, Colin

[psu_mod.zip](https://github.com/timperi/c64-wedge-psu-pcb/files/7928933/psu_mod.zip)

**Comment by timperi** [comment]
Hello Colin!
Thank you for spotting my mistake, really shows my inexperience in designing circuits. I appreciate someone with more knowledge taking a look at this! I'll make a correction as you suggested when I have time.

**Comment by ColinDavies71** [comment]
Here is a quick fix to try out, You need to cut a track and drill a 
small hole to move the R1 resistor.

This could also use a 200R Trimmer if you wanted to make it adjustable.

Kind Regards. Colin
![c64-wedge-psu-pcb-top_mod](https://user-images.githubusercontent.com/14298402/151028449-2d300174-5b62-414c-90a2-b15330e3d615.png)

**Comment by timperi** [comment]
Alright, that's a good solution for existing boards, thanks!
Yes there could be a trimmer also, but these are mostly targeted for a specific voltage as you know, so a fixed resistor works well.

**Comment by timperi** [comment]
I've edited the files to fix this. Hopefully I got it right. I ordered some protos from pcbway to test this. After those arrive, and there are no problems, I'll update the images too.

**Comment by timperi** [comment]
I'd really like to thank you Colin for taking the time and verifying this, I really appreciate it!
When the new boards arrive, I could send you a few free of charge, if you'd like.

**Comment by timperi** [comment]
Tested the new design, and adjusted the divider resistor values. Found out that the led resistor doesn't fit anymore, so repositioned that. Also did some minor layout changes. Issue is now solved.
